# Generated by Django 2.1.4 on 2019-02-03 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('username_id', models.CharField(max_length=100, null=True)),
                ('uuid', models.CharField(max_length=100, null=True)),
                ('rank_token', models.CharField(max_length=100, null=True)),
                ('token', models.CharField(max_length=200, null=True)),
                ('is_logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramFavoriteAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.InstagramAccount')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramFollowedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('is_followed', models.BooleanField()),
                ('is_following', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.InstagramAccount')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.InstagramAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Member'),
        ),
    ]
