# Generated by Django 2.1.4 on 2019-02-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190204_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccountSetting',
            fields=[
                ('instagram_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.InstagramAccount')),
                ('start_at_h', models.IntegerField(default=9)),
                ('start_at_m', models.IntegerField(default=0)),
                ('end_at_h', models.IntegerField(default=23)),
                ('end_at_m', models.IntegerField(default=59)),
                ('like_per_day', models.IntegerField(default=1000)),
                ('media_min_like', models.IntegerField(default=0)),
                ('media_max_like', models.IntegerField(default=0)),
                ('follow_per_day', models.IntegerField(default=0)),
                ('follow_time', models.IntegerField(default=18000)),
                ('user_min_follow', models.IntegerField(default=0)),
                ('user_max_follow', models.IntegerField(default=0)),
                ('follow_time_enabled', models.BooleanField(default=True)),
                ('unfollow_per_day', models.IntegerField(default=0)),
                ('unfollow_recent_feed', models.BooleanField(default=True)),
                ('unlike_per_day', models.IntegerField(default=0)),
                ('time_till_unlike', models.IntegerField(default=259200)),
                ('comments_per_day', models.IntegerField(default=0)),
                ('comment_list', models.CharField(default="[['like']]", max_length=5000)),
                ('tag_list', models.CharField(default="['f4f']", max_length=2000)),
                ('tag_blacklist', models.CharField(default='[]', max_length=2000)),
                ('user_blacklist', models.CharField(default='{}', max_length=2000)),
                ('max_like_for_one_tag', models.IntegerField(default=5)),
                ('unfollow_break_min', models.IntegerField(default=15)),
                ('unfollow_break_max', models.IntegerField(default=30)),
            ],
        ),
    ]
