# Generated by Django 2.1.4 on 2019-02-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_instagramaccountsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccountsetting',
            name='process_id',
            field=models.IntegerField(default=0),
        ),
    ]
